import { Card } from './ui/card';
import { Badge } from './ui/badge';
import { AIInsight } from '../types';
import { GraduationCap, Users, Building2, Shield, Github, Award, TrendingUp, AlertCircle, Lightbulb, Wrench } from 'lucide-react';

interface AIInsightsProps {
  candidateId: string;
}

export function AIInsights({ candidateId }: AIInsightsProps) {
  // Mock insights - in real app, these would be generated by AI
  const insights: AIInsight[] = [
    {
      id: '1',
      type: 'strength',
      category: 'Education',
      title: 'Ph.D. in Computer Science - Research Asset',
      description: 'Having a Ph.D. makes this candidate exceptionally valuable for research-oriented projects and can mentor junior team members in advanced ML concepts.',
      confidence: 98,
    },
    {
      id: '2',
      type: 'strength',
      category: 'Leadership',
      title: 'Strong Leadership Potential',
      description: 'Communication skills, publication record, and experience collaborating with cross-functional teams indicate high potential as a technical lead or team lead.',
      confidence: 92,
    },
    {
      id: '3',
      type: 'strength',
      category: 'Experience',
      title: 'Similar Product Experience',
      description: 'Previously worked at a competitor building similar ML-powered products. This experience can accelerate onboarding and provide valuable industry insights.',
      confidence: 95,
    },
    {
      id: '4',
      type: 'opportunity',
      category: 'Skills',
      title: 'Strong Open Source Contributions',
      description: 'Active contributor to major ML frameworks (TensorFlow, PyTorch). Strong GitHub profile with 2.5k+ stars across repositories indicates technical expertise and community respect.',
      confidence: 96,
    },
    {
      id: '5',
      type: 'opportunity',
      category: 'Online Presence',
      title: 'Excellent Online Presence',
      description: 'Maintains active LinkedIn (15k followers), Medium blog (50+ articles), and Stack Overflow (top 5% contributor). Shows thought leadership and communication skills.',
      confidence: 94,
    },
    {
      id: '6',
      type: 'opportunity',
      category: 'Additional Skills',
      title: 'Skills Not in JD: Distributed Systems',
      description: 'Candidate has strong experience with distributed systems and large-scale infrastructure - not required for the role but could be valuable for scaling initiatives.',
      confidence: 88,
    },
    {
      id: '7',
      type: 'training',
      category: 'Training',
      title: 'Minimal Training Required',
      description: 'Estimated 2-3 weeks to fully ramp up on internal tools and processes. Technical skills are already at required level or above.',
      confidence: 90,
    },
  ];

  const getIcon = (category: string) => {
    switch (category.toLowerCase()) {
      case 'education': return GraduationCap;
      case 'leadership': return Users;
      case 'experience': return Building2;
      case 'skills': return Award;
      case 'online presence': return TrendingUp;
      case 'additional skills': return Lightbulb;
      case 'training': return Wrench;
      default: return AlertCircle;
    }
  };

  const getTypeColor = (type: string) => {
    switch (type) {
      case 'strength': return 'bg-green-100 text-green-700 border-green-200';
      case 'opportunity': return 'bg-blue-100 text-blue-700 border-blue-200';
      case 'concern': return 'bg-yellow-100 text-yellow-700 border-yellow-200';
      case 'training': return 'bg-purple-100 text-purple-700 border-purple-200';
      default: return 'bg-gray-100 text-gray-700 border-gray-200';
    }
  };

  return (
    <Card className="p-4">
      <h3 className="text-gray-900 mb-4">AI-Powered Insights</h3>
      <div className="space-y-3">
        {insights.map((insight) => {
          const Icon = getIcon(insight.category);
          return (
            <div
              key={insight.id}
              className={`p-3 rounded-lg border ${getTypeColor(insight.type)}`}
            >
              <div className="flex items-start gap-3">
                <Icon className="size-5 mt-0.5 flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <p className="text-sm">{insight.title}</p>
                    <Badge variant="outline" className="text-xs">
                      {insight.confidence}% confidence
                    </Badge>
                  </div>
                  <p className="text-xs opacity-90">{insight.description}</p>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Auto-generated hiring message */}
      <div className="mt-4 p-4 bg-gradient-to-br from-purple-50 to-blue-50 rounded-lg border border-purple-200">
        <h4 className="text-sm text-gray-900 mb-2">🤖 Auto-Generated Outreach Message</h4>
        <p className="text-sm text-gray-700 leading-relaxed">
          Hi Dr. Chen,
          <br /><br />
          I came across your profile and was impressed by your Ph.D. in Computer Science and extensive experience in ML research. Your work on NLP and computer vision, particularly your contributions to TensorFlow and PyTorch, aligns perfectly with our current initiatives.
          <br /><br />
          We're looking for someone with your research background and technical depth to join our ML team. Your experience building production systems at [Previous Company] working on similar products would be invaluable as we scale our AI capabilities.
          <br /><br />
          Would you be interested in a conversation about this opportunity?
          <br /><br />
          Best regards
        </p>
      </div>
    </Card>
  );
}
